### PR TITLE
Create README-ja.md

### PR DESCRIPTION
**Pull request by t-cool**
I translated the README.me into Japanese.  I hope more and more Japanese users will use this repository if we have a Japanese version of README. I'll update its Japanese version following official master branch's update.

### CODE REVIEW

**Comment by MrOffline77** [comment]
Hi, @t-cool thats very cool thank you !

**Comment by MrOffline77** [comment]
If you want so, you can also translate the php-X Branches and its Readme.

**Comment by t-cool** [comment]
@MrOffline77 
All right! I'll translate them too later!

**Comment by MrOffline77** [comment]
Cool thank you very much !

**Pull request merged**
