### PR TITLE
Add NPM/Node support + Examples of local hosts in the host file

### PR DESCRIPTION
**Pull request by danielefavi**
I added some new functionalities to your awesome repo. Feel free to keep or discard any changes you want.

List of changes:

### 1) Node / NPM support
Often the developers need to compile JS projects. So I added a new file `docker-compose.node.yml` for compiling JS projects (like is needed on Laravel) to run separately NPM commands.
For example the command below run the *watch* command on a laravel project:
```
docker-compose -f docker-compose.node.yml run node bash -c "cd laravel-app && npm run watch"
```

### 2) Example of virtual hosts in the file
I added commented examples of virtual hosts in the file `config/vhosts/default.conf`.
The virtual host examples are for a Laravel, Wordpress and plain PHP project.

### 4) Small change to the index.php

### CODE REVIEW

**Review by yayas87 — APPROVED** [review]
Looks good to me

**Comment by MrOffline77** [comment]
Hi, thanks for contributing to this project. 
This looks quite interesting. I'm going to test this on the weekend and then I let you know if I see any issues.

**Comment by fefoweb** [comment]
I have some doubts about whether to use a specific docker-compose to instantiate node services.

Couldn't the various Dockerfiles related to webservers (in docker-compose-lamp/bin/php**) be modified to include the installation of node? 

I also suggest, instead of installing node, to use nvm that allows you to have and manage multiple versions of node within the same environment...

**Comment by danielefavi** [comment]
@fefoweb  Instead I don't see any benefit on installing NVM within the PHP container for the following reasons:
- A PHP webserver becomes also a Node server.
- Extra (and useless) work on editing each Docker file within the all the PHP bin folder when you can achieve the same result with the simple file docker-compose.node.yml
- Docker gives you the opportunity to keep the environment separate, why do you want to install different environments (Apache + Node) on each webserver and risk compromising the stability?
- Test every single PHP webserver again.

In my opinion, this repo should be focused on the LAMP stack and not a LAMP+NODE stack because things can get complicated.  

The separate node YML file helps the full-stack and frontend developers to compile their JS files without complicating the LAMP stack.

**Comment by fefoweb** [comment]
@danielefavi Certainly. 
I can agree in general on everything you say: this depends a lot on how the docker environment we are talking about is thought about and also on what is the attitude or not to put hands on dockerized instances.

I would like to point out for the benefit of discussion that:

* The PHP webserver remains as such. Installing nvm does NOT mean installing node (and therefore the npm ecosystem) but simply having the executable in the webserver volume with which, if needed, you can have an instance of node/npm installed.
* I might agree with your third point but at that point I would put a volume with a node instance directly in the original docker-compose, not making another one.
* In general, it's good to do client-side builds outside of dockerized instances for speed: that's why I would never create new volumes with node instances to build sources, which I could do outside of the docker environment much faster.

My comments about the changes to the README.md file remain in effect: changes that are closely related to your changes and remove several references that, in my opinion, should remain intact.

**Comment by MrOffline77** [comment]
stale => close

**Pull request closed without merging**
