### PR TITLE
Environment variables

### PR DESCRIPTION
**Pull request by sebastian-serfe**
- Added environment variables to "un-hardcode" hots machine ports when, for example, you have a lamp installed on yout computer

- Added environments variables to initialize mysql with a database and user with granted permissions

### CODE REVIEW

**Comment by sebastian-serfe** [comment]
@narendravaghela requested changes done. Thanks!

**Comment by narendravaghela** [comment]
Thanks @sebastian-serfe

**Comment by sebastian-serfe** [comment]
Thanks to you for create this helpful stack @narendravaghela

**Comment by narendravaghela** [comment]
I am glad to know that it is helping people like you and the other developers in the community.

**Pull request merged**
